app/models/post.py
from datetime import datetime
from app import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return 'Post {}>'.format(self.body)

app/models/user.py
from app import db, login
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from app.models.post import Post

followers = db.Table('followers',
                     db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
                     db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
                     )


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    about_me = db.Column(db.String(140))
    last_seen = db.Column(db.DateTime, default=datetime.utcnow)
    followed = db.relationship(
        'User', secondary=followers,
        primaryjoin=(followers.c.follower_id == id),
        secondaryjoin=(followers.c.followed_id == id),
        backref=db.backref('followers', lazy='dynamic'), lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)

    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id).count() > 0

    def followed_posts(self):
        followed = Post.query.join(followers,
                               (followers.c.followed_id == Post.user_id)).filter(
                                   followers.c.follower_id == self.id)
        own = Post.query.filter_by(user_id=self.id)
        return followed.union(own).order_by(Post.timestamp.desc())


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length


class PostForm(FlaskForm):
    post = TextAreaField('Say something', validators=[DataRequired(), Length(min=1, max=140)])
    submit = SubmitField('Submit')


class EmptyForm(FlaskForm):
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from config import Config
from flask_avatars import Avatars
from flask_moment import Moment

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
login = LoginManager()
login.login_view = 'auth.login'
avatars = Avatars()
moment = Moment()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)
    login.init_app(app)
    avatars.init_app(app)
    moment.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)
    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp)
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    return app


from app.models import user, post

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from datetime import datetime
from app import db
from app.main.forms import PostForm, EmptyForm
from app.models.user import User
from app.models.post import Post


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@bp.route('/feed', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@bp.route('/', methods=['GET', 'POST'])
@login_required
def feed():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=str(form.post), author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post is now live!')
        return redirect(url_for('main.feed'))
    posts = current_user.followed_posts()
    return render_template('main/feed.html', title='Home page', posts=posts, form=form)


@bp.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts
    form = EmptyForm()
    return render_template('main/user.html', user=user, posts=posts, form=form)


@bp.route('/follow/<username>', methods=['GET', 'POST'])
@login_required
def follow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found'.format(username))
        return redirect(url_for('main.feed'))
    current_user.follow(user=user)
    if user == current_user:
        flash('You cannot follow yourself!')
        return redirect(url_for('main.user', username=username))
    current_user.follow(user)
    db.session.commit()
    flash('You are following {} now!'.format(username))
    return redirect(url_for('main.user', username=username))


@bp.route('/unfollow/<username>', methods=['GET', 'POST'])
@login_required
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        flash('User {} not found'.format(username))
        return redirect(url_for('main.feed'))
    current_user.follow(user=user)
    if user == current_user:
        flash('You cannot unfollow yourself!')
        return redirect(url_for('main.user', username=username))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following {} now!'.format(username))
    return redirect(url_for('main.user', username=username))

app/templates/main/_control_panel.html
<div class="container" style="width: 150px">
    <ul class="nav flex-column" style="width: 120px">
        <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{ url_for('main.user', username=current_user.username) }}">
                <img src="{{ url_for('static', filename = 'icons/house.svg') }}"> My page</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.feed') }}">
                <img src="{{ url_for('static', filename = 'icons/newspaper.svg') }}"> Feed</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <img src="{{ url_for('static', filename = 'icons/chat.svg') }}"> Messages</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <img src="{{ url_for('static', filename = 'icons/people.svg') }}"> Friends</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <img src="{{ url_for('static', filename = 'icons/list.svg') }}"> Discover</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
                <img src="{{ url_for('static', filename = 'icons/gear.svg') }}"> Settings</a>
        </li>
    </ul>
</div>

app/templates/main/_post.html
<table>
    <tr>
        <td><img src={{ avatars.gravatar(post.author.email, 36) }}></td>
        <td>
            <table>
                <tr>
                    <td style="padding-left: 10px" align="left">{{ post.author.username }}</td>
                </tr>
                <tr>
                    <td style="padding-left: 10px">{{ post.body }}</td>
                </tr>
            </table>
        </td>
    </tr>
    <hr style="width: 950px; margin-left: 40px">
</table>

app/templates/main/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}
    {{ title }} - APP
    {% else %}
    <title>APP</title>
    {% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default" style="min-width: 1252px">
        <div class="container">
            <div class="navbar-header">
                <table>
                    <tr>
                        <td>
                            <a class="navbar" style="text-decoration: none" href="{{ url_for('main.feed') }}">
                                <img src="{{ url_for('static', filename = 'icons/people-fill.svg') }}">
                                <b>APP</b>
                            </a>
                        </td>
                        <td style="padding-left: 770px">
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}">Logout</a>
                            {% else %}
                            <a href="{{ url_for('auth.login') }}">Login</a>
                            {% endif %}
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <div class="alert alert-info">{{ message }}</div>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        <table class="tab-content">
            <tr>
                <td>
                    {% if current_user.is_authenticated %}
                    {% include 'main/_control_panel.html' %}
                    {% endif %}
                </td>
                <td class="text-center" style="width: 1000px">
                    {% block app_content %}{% endblock %}
                </td>
            </tr>
        </table>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
{% endblock %}

app/templates/main/feed.html
{% extends 'main/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Hi, {{ current_user.username }}!</h1>
    {% if form %}
    {{ wtf.quick_form(form) }}
    {% endif %}
    {% for post in posts %}
    <div><p>{{ post.author.username }} says: <b>{{ post.body }}</b></p></div>
    {% endfor %}
{% endblock %}

app/templates/main/index.html
{% extends 'main/base.html' %}

{% block app_content %}
    <h1>Hi, {{ current_user.username }}!</h1>
    {% for post in posts %}
    <div><p>{{ post.author.username }} says: <b>{{ post.body }}</b></p></div>
    {% endfor %}
{% endblock %}

app/templates/main/user.html
{% extends 'main/base.html' %}

{% block app_content %}
    <table>
        <tr>
            <td>
                <img src={{ avatars.gravatar(user.email)}}>
                {% if user == current_user %}
                <p><a href="">Edit your profile</a></p>
                {% elif not current_user.is_following(user) %}
                <p>
                    <form action="{{ url_for('main.follow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Follow' , class_='btn btn-default') }}
                    </form>
                </p>
                {% else %}
                <p>
                    <form action="{{ url_for('main.unfollow', username=user.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value='Unfollow', class_='btn btn-default') }}
                    </form>
                </p>
                {% endif %}
            </td>
            <td>
                <table>
                    <tr>
                        <td style="padding-left: 10px" align="left"><h1>{{ user.username }}</h1></td>
                        <td style="padding-left: 350px">{% if user.last_seen %}<p>Last seen on {{ moment(user.last_seen).format('LLL') }}</p>{% endif %}</td>
                    </tr>
                    <tr>
                        <td style="padding-left: 10px">{% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    {% for post in posts %}
    {% include 'main/_post.html' %}
    {% endfor %}
{% endblock %}